name: CI

on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: |
          echo "Running PR code"
          env
        env:
          SECRET_TOKEN: ${{ secrets.FLAG }}
